name: AWS Code Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - name: Set AWS region
        run: aws configure set region us-east-1

      - name: Run AWS CodeDeploy
        run: aws deploy create-deployment --application-name "webapp_" --deployment-group-name "github_deploy_gp" --github-location repository="masakan590/AWS_cd",commitId="${{ github.sha }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_tOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
